// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdusgurjkmdroacxtrtb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkdXNndXJqa21kcm9hY3h0cnRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMTEwMDgsImV4cCI6MjA2MzY4NzAwOH0.Kpq_kpqiT74BmHZx9AlRGjTJSzZ3O4WfkkCRZ4wfuDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
